/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'russb' at '10/30/15 9:53 AM' with Gradle 2.3
 *
 * @author russb, @date 10/30/15 9:53 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
