/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'russb' at '10/30/15 9:53 AM' with Gradle 2.3
 *
 * @author russb, @date 10/30/15 9:53 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
